const ALL_API ="http://www.cm-innovationlab.it:5000/api/v2/list/all";               //This is the API on my website to get all lists
const RELIABLE_API ="http://www.cm-innovationlab.it:5000/api/v2/list/reliable";		//This is the API on my website to get white list
const MALICIOUS_API ="http://www.cm-innovationlab.it:5000/api/v2/list/malicious";	//This is the API on my website to get black list
const INFERENCE_API ="http://www.cm-innovationlab.it:5000/api/v2/url/inference";	//This is the API on my website to get prediction
const ADD_API ="http://www.cm-innovationlab.it:5000/api/v2/url/add";		        //This is the API on my website to add new page in white list
const BAD_API ="http://www.cm-innovationlab.it:5000/api/v2/url/bad";		        //This is the API on my website to add new page in black list
const CORRECTION_API ="http://www.cm-innovationlab.it:5000/api/v2/url/correction";	//This is the API on my website to change page from black to white list
const PAPER = 'https://ceur-ws.org/Vol-3260/paper13.pdf';
const RANALDI_MODEL = 'https://github.com/LeonardRanaldi/ItalianPhishingDetection/blob/main/models/RNN%20word%2Bchar_emb.ipynb';
const FIREFOX_PRIVACY_SETTINGS = 'https://support.mozilla.org/en-US/kb/block-deceptive-content-and-dangerous-downloads-firefox';
const FIREFOX_FILE_TYPES_BEHAVIOR = 'https://support.mozilla.org/en-US/kb/change-firefox-behavior-when-open-file';